name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore BulkDDSConverter.csproj

    - name: Publish
      run: dotnet publish BulkDDSConverter.csproj -c Release -r win-x64 --self-contained true -o publish

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Zip Build
      run: |
        powershell Compress-Archive -Path publish\* -DestinationPath BulkDDSConverter.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: BulkDDSConverter.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}